### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by mattpang** [LaustinSpayce/Sailing-Ship#1]
You made me want to learn unity now!

I've gotten your code running, just trying to modify it so the boat slowly slows down instead of the sudden stop.

**Comment by mattpang** [comment]
I've added some wind logic and the slow down. Unity is pretty nice, I've not done C# before but it's not so bad. I don't like the need for curly braces for mutli-line if statements though.

**Comment by LaustinSpayce** [comment]
Hey man, welcome!

I'm considering having a "throttle" sort of control for the boat. But not committed to anything specifically for it.

I've never really done programming before, so this is my first project. Trying to keep things really simple as I'm totally green/noob to coding.
